import Foundation
import CodexNCore

@main
struct TestRunner {
    static func main() throws {
        try createsEmptyProfileDirectoriesWithoutCodexConfig()
        try createsProfilesWithResolvedCodexAppBundle()
        try refusesToCreateOverNonEmptyProfileDirectory()
        try rejectsProfileIDsWithPathLikeCharacters()
        try importsDefaultCodexHomeAndElectronData()
        try createsAPIKeyProfileWithoutLeakingKeyToConfig()
        try rejectsInvalidAPIKeyProviderID()
        try rejectsAPIKeyProfileInputsWithIllegalCharacters()
        try rejectsInvalidAPIKeyBaseURL()
        try rejectsAPIKeyConfigValuesWithControlCharacters()
        try protectsProfileRegistryAndDirectoriesWithOwnerOnlyPermissions()
        try tightensExistingProfileRegistryPermissions()
        try buildsLaunchCommandsWithProfileIsolation()
        try fallsBackToChatGPTCodexBundleWhenLegacyCodexAppIsMissing()
        try injectsAPIKeyEnvironmentIntoLaunchCommands()
        try readsLegacyProfileRegistry()
        try buildsDefaultLaunchCommandsWithoutProfileIsolation()
        try buildsDefaultReopenCommandsWithoutNewInstanceFlag()
        try stripsCodexEnvironmentWhenLaunchingDefaultApp()
        try resolvesFocusedManagedProfileFromExplicitProfileEnvironment()
        try resolvesFocusedManagedProfileFromExplicitProfileArgument()
        try resolvesFocusedManagedProfileFromCodexHomeEnvironment()
        try resolvesFocusedManagedProfileFromElectronUserDataEnvironment()
        try resolvesFocusedManagedProfileFromUserDataDirArgument()
        try resolvesDefaultCodexForCodexAppWithoutProfileMatch()
        try resolvesDefaultCodexForChatGPTCodexAppWithoutProfileMatch()
        try selectsRunningManagedProfileToActivate()
        try selectsRunningDefaultCodexToActivate()
        try skipsCodexHelperProcessesWhenSelectingDefaultToActivate()
        try plansToReopenRunningCodexWhenMatchedAppHasNoVisibleWindow()
        try plansToActivateRunningCodexWhenMatchedAppHasVisibleWindow()
        try returnsNilWhenNoRunningCodexProcessMatchesActivationTarget()
        try ignoresNonCodexForegroundApps()
        try formatsFocusedProfileMenuTitles()
        try formatsFocusedProfileMenuBarText()
        try identifiesFocusedProfileTitleHighlightSegment()
        try formatsMenuBarUsageTitles()
        try skipsProcessArgumentReadsForNonCodexApps()
        try delaysWorkspaceDrivenMenuBarTitleUpdates()
        try usesTenSecondFocusedProfileFallbackInterval()
        try parsesKernelProcessArgumentsAndEnvironment()
        try scansTodayUsageFromCodexHomes()
        try scansRecentlyModifiedOlderCodexSessionPartitionsOnly()
        try computesUsageListBarWidths()
        try formatsTokenUsageValues()
        try recognizesSettingsWindowCloseShortcut()
        try writesAndReadsUsageCache()
        print("CodexNCoreTestRunner: all tests passed")
    }
}
